// creating an array and passing the number, questions, options, and answers
let questions = [
    {
    numb: 1,
    question: "What is xQc known for?",
    answer: "OverWatch League Professional",
    options: [
      "OverWatch League Professional",
      "Streaming",
      "Lots of Drama",
      "Youtube"
    ]
  },
    {
    numb: 2,
    question: "What is xQc's real name??",
    answer: "Felix",
    options: [
      "Felix",
      "Alex",
      "Cody",
      "Mirin"
    ]
  },
    {
    numb: 3,
    question: "What does the ow in xQcow stand for?",
    answer: "OverWatch",
    options: [
      "UpWhen",
      "UnderWhelmed",
      "OverWatch",
      "UpperWealth"
    ]
  },
    {
    numb: 4,
    question: "What does xQc say to new subs on Twitch",
    answer: "Welcome To The Jungle",
    options: [
      "Much love",
      "Thanks for the sub!",
      "Nothing",
      "Welcome To The Jungle"
    ]
  },
    {
    numb: 5,
    question: "What does xQc cal his subs",
    answer: "Juicers",
    options: [
      "Juicers",
      "Losers",
      "Fans",
      "Mini x's"
    ]
  },
  
];